import React from 'react'
import './navbar.css'

export default function Home() {
  return (
    <div className='container'>
      <h1>Home</h1>
      <p className='p-tag' >Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo ipsum facere quisquam sed rerum nam quidem iusto, eos ducimus, modi voluptate ad maiores quos voluptatibus cupiditate soluta dolore, expedita officia.</p>
      <p className='p-tag'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam sequi nostrum omnis, aut expedita ullam odit deserunt mollitia iusto sed nesciunt deleniti ad veniam velit, possimus doloribus delectus, molestias officiis commodi tempore repudiandae architecto! Eaque soluta eligendi magni, qui, ab sapiente reprehenderit sequi, voluptas ducimus laborum nesciunt temporibus illo! Sapiente non alias earum minima nisi vitae, nihil laborum ad nobis aliquam architecto ratione. Incidunt eum labore porro voluptatem temporibus. Quis odit quaerat vitae autem, sit, cumque suscipit aperiam cupiditate rerum illo quas ea hic adipisci soluta saepe animi, provident assumenda tempora quia? Perferendis enim aliquam nam magnam harum amet voluptatum suscipit? Nobis, magni quod ducimus minima ex alias sunt sint, quo repudiandae sit, laborum at. Fuga maxime, sunt tenetur animi enim excepturi ipsum provident voluptas eos. Iusto maiores quia exercitationem accusantium, unde labore saepe nesciunt! Excepturi vitae laboriosam ea inventore possimus. Eaque omnis non rem inventore eos voluptatibus cum necessitatibus expedita repudiandae error veniam eligendi, quae assumenda sapiente aliquam fugit eius ea minus id blanditiis repellendus nulla impedit atque reprehenderit! Amet impedit saepe eius praesentium itaque ex, perspiciatis quisquam libero obcaecati maxime enim sed autem dolorem labore. Voluptas, hic. Exercitationem obcaecati praesentium, nostrum est fuga consectetur vel at officia nisi impedit iste, veniam accusantium deserunt! Necessitatibus ipsa tempore repudiandae, consectetur culpa in perspiciatis velit animi laborum architecto perferendis labore tempora excepturi harum id cupiditate ipsum voluptatibus assumenda? Harum, possimus? Et labore necessitatibus rerum iste mollitia illo harum natus sequi rem, repudiandae tempore, itaque vitae optio magni voluptates eum temporibus? Quam quod saepe fugiat voluptates amet similique nostrum! Vel ea, maxime rem aspernatur culpa incidunt itaque ratione nulla rerum ipsa exercitationem impedit ipsam dolorum ab unde consequuntur non quisquam? Quo maiores repellendus, exercitationem unde voluptatum placeat non hic dolores assumenda accusamus nisi similique iusto. Laudantium aperiam vero rerum optio ipsum consectetur alias id temporibus? Et illo illum pariatur nostrum totam, numquam atque voluptatum, tempora quam esse labore nisi, fugit ad doloremque molestiae? Quae illo sunt, eveniet eaque deserunt commodi repellendus. Similique debitis magnam atque quo magni hic cum blanditiis, dicta pariatur quod perferendis dolorem voluptas voluptatem? Id beatae eaque necessitatibus vitae.</p>
      <p className='p-tag'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae fuga assumenda dolorem dolore officiis dicta recusandae iure sunt! Nobis ad reprehenderit doloremque, nulla ea impedit magni repellat officiis maiores voluptates.</p>
    </div>
  )
}
